services:
  - type: web
    name: kokan-backend
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: development
    plan: free
    region: singapore